/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/WawaOffice.glb
*/

import React, {useLayoutEffect} from 'react'
import {useGLTF, useScroll} from '@react-three/drei'
import { useRef } from 'react'
import gsap from "gsap";
import {useFrame} from "@react-three/fiber";
export const floorHeight = 2.214;
export const noOfFloors = 3;

export function Office(props) {
    const ref = useRef()
    const libraryRef= useRef()
    const atticRef= useRef()
    const tl= useRef()

    const scroll = useScroll();

    useFrame(()=>{
        tl.current.seek(scroll.offset*tl.current.duration())
    })


    useLayoutEffect(()=>{
tl.current = gsap.timeline()
        tl.current.to(
    ref.current.position,{
        duration:4,
        y: -floorHeight*(noOfFloors-1),
    }, 0);



        tl.current.to(libraryRef.current.position,{
            duration: 2,
            x: 0,
            z: 0
        }, 0);



        // tl.current.to(atticRef.current.position,{
        //     duration: 0,
        //     x: 0,
        //     z: -6.199
        // }, 0);



        // tl.current.to(atticRef.current.position,{
        //     duration: 0,
        //     x: -1.97,
        //     z: -2.199
        // }, 0);

        tl.current.to(atticRef.current.position,{
            duration: 4,
            x: 0,
            z: 0
        }, 0);


    },[])

    const { nodes, materials } = useGLTF('./models/WawaOffice.glb')
    return (
        <group {...props} dispose={null} ref={ref}>
            <mesh geometry={nodes['01_office'].geometry} material={materials['01']} />
            <group position={[0, 2.114, -2.23]} ref={libraryRef}>
            <mesh geometry={nodes['02_library'].geometry} material={materials['02']}  />
            </group>
            <group position={[0, 4.227, -6.199]}  ref={atticRef}>
                <mesh geometry={nodes['03_attic'].geometry} material={materials['03']}  />
            </group>
        </group>
    )
}

useGLTF.preload('/WawaOffice.glb')
